name = "HEROBrowser"
version = "0.1.0"
type = "exec"
language = "cpp"

[sources]
dirs = ["src"]

[includes]
dirs = ["include"]




# SDL2 and SDL2_ttf should be installed system-wide
# On Ubuntu/Debian: sudo apt-get install libsdl2-dev libsdl2-ttf-dev
# On macOS: brew install sdl2 sdl2_ttf
# On Windows: Use vcpkg or download from libsdl.org
[build]
flags = ["-Wall", "-Wextra", "-Wpedantic", "-std=c++20"]
optimization = "2"
libs = ["SDL2", "SDL2_ttf"]
[scripts]
prebuild = "echo 'Make sure SDL2 and SDL2_ttf are installed'"
postbuild = "echo 'Build complete - Run with: ./build/HEROBrowser'"
